apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hgxwqn24p-python 
  janus-idp.io/tekton: hgxwqn24p-python
  backstage.io/kubernetes-id: hgxwqn24p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hgxwqn24p-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml